server:
  port: 8080
  tomcat:
    max-swallow-size: -1
    max-http-form-post-size: -1

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pjy?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: Taojiang530#
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

doubao:
  api-key: ark-3e904f0e-fe4a-4076-bb48-2d4ed85c19ad-dc280
  endpoint: https://ark.cn-beijing.volces.com/api/v3
  model: ep-20260417184618-2lnhf

kimi:
  api-key: sk-13ZJd5BLd5ZVI1uysEuuOgEVEXOKfxq2tgxrX7zHsW1E4qjd
  endpoint: https://api.moonshot.cn/v1
  model: kimi-k2.6
